version: '3.8'

services:
  # MySQL service
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"

  # Redis service
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    depends_on:
      - mysql

  # Elasticsearch service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    depends_on:
      - mysql

  # Sidekiq worker
  sidekiq:
    build: .
    command: "bundle exec sidekiq"
    container_name: sidekiq
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      RAILS_ENV: production
      RAILS_MASTER_KEY: 52e2333ee247fada908ec92322556a6d
      MYSQL_HOST: mysql
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root_password
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - elasticsearch

  # cron job service
  job:
    build: .
    container_name: job
    command: "bash -c 'while :; do sleep 120 && bundle exec rake update_counts:chats_and_messages_counts; done'"
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      RAILS_ENV: production
      RAILS_MASTER_KEY: 52e2333ee247fada908ec92322556a6d
      MYSQL_HOST: mysql
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root_password
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - rails

  # Rails application service
  rails:
    build: .
    container_name: rails
    command: >
      bash -c "
         /usr/local/bin/wait-for-it -t 0 mysql:3306 &&
         ./bin/rails db:create && ./bin/rails db:migrate &&
        ./bin/rails server
      "
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      RAILS_ENV: production
      RAILS_MASTER_KEY: 52e2333ee247fada908ec92322556a6d
      MYSQL_HOST: mysql
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root_password
      REDIS_URL: redis://redis:6379/0
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - redis
      - elasticsearch
      - sidekiq
