default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['MYSQL_USERNAME'] || 'chatSystem' %>
  host: <%= ENV['MYSQL_HOST'] || 'localhost' %>
  database: <%= ENV['MYSQL_DATABASE'] || 'chat_system_DB' %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
